### ISSUE TITLE
FR: Ecriture inclusive

### ISSUE THREAD

**Issue by sylr** [peritext/ovide#2]
Personellement je ne suis pas un grand fan de ce style d'écriture donc je voulais savoir si c'est négociable ?

Est-ce qu'a la place de ce style on ne pourrait pas simplement citer la forme masculine et féminine ? .i.e. : `auteur.e` -> `auteur et/ou autrice`

Cordialement.

**Comment by robindemourat** [comment]
Merci pour ce retour ! oui pourquoi pas c'est en effet plus élégant, il faudrait juste vérifier que des labels plus longs ne cassent pas l'UI dans tous les cas concernés (je regarderai un de ces jours, sinon PR bienvenue).

Cordialement
